exports.myData = [ {
    name: "Chioma",
    surname: "Ify",
    age: "24",
    height: "6ft",
    bloodgroup: "O",
    favoriteFood: "Rice",
    colour: "Yellow",
    hometown: "Mbano",
    siblings: "2",
},
{
    name: "Jessy",
    surname: "James",
    age: "26",
    height: "4ft",
    bloodgroup: "O+",
    favoriteFood: "Yam",
    colour: "Yellow",
    hometown: "Umuahia",
    siblings: "10",

},
{
    name: "Donald",
    surname: "Trump",
    age: "56",
    height: "4ft",
    bloodgroup: "O+",
    favoriteFood: "Yam",
    colour: "Yellow",
    hometown: "Umuahia",
    siblings: "10",

},
{
    name: "Chibuike",
    surname: "thompson",
    age: "26",
    height: "4.5ft",
    bloodgroup: "O",
    favoriteFood: "Yam",
    colour: "Blue",
    hometown: "agueri",
    siblings: "12",
},
]
